module.exports =  todoList = [
    { "id": 1, "title": "Task 1", "description": "Complete project documentation", "completed": false },
    { "id": 2, "title": "Task 2", "description": "Read new research paper", "completed": true },
    { "id": 3, "title": "Task 3", "description": "Update client on progress", "completed": false },
    { "id": 4, "title": "Task 4", "description": "Test API integration", "completed": true },
    { "id": 5, "title": "Task 5", "description": "Clean workspace", "completed": false },
    { "id": 6, "title": "Task 6", "description": "Plan the next sprint", "completed": true },
    { "id": 7, "title": "Task 7", "description": "Fix UI bugs", "completed": false },
    { "id": 8, "title": "Task 8", "description": "Deploy application to server", "completed": true },
    { "id": 9, "title": "Task 9", "description": "Conduct code review", "completed": false },
    { "id": 10, "title": "Task 10", "description": "Refactor old code", "completed": true },
    { "id": 11, "title": "Task 11", "description": "Prepare presentation slides", "completed": false },
    { "id": 12, "title": "Task 12", "description": "Write unit tests", "completed": true },
    { "id": 13, "title": "Task 13", "description": "Schedule team meeting", "completed": false },
    { "id": 14, "title": "Task 14", "description": "Research new technologies", "completed": true },
    { "id": 15, "title": "Task 15", "description": "Optimize database queries", "completed": false },
    { "id": 16, "title": "Task 16", "description": "Submit report to manager", "completed": true },
    { "id": 17, "title": "Task 17", "description": "Backup project files", "completed": false },
    { "id": 18, "title": "Task 18", "description": "Review pull requests", "completed": true },
    { "id": 19, "title": "Task 19", "description": "Write a blog post", "completed": false },
    { "id": 20, "title": "Task 20", "description": "Check email for client feedback", "completed": true },
    { "id": 21, "title": "Task 21", "description": "Research market trends", "completed": false },
    { "id": 22, "title": "Task 22", "description": "Test new feature implementation", "completed": true },
    { "id": 23, "title": "Task 23", "description": "Update software documentation", "completed": false },
    { "id": 24, "title": "Task 24", "description": "Fix server issues", "completed": true },
    { "id": 25, "title": "Task 25", "description": "Attend online webinar", "completed": false },
    { "id": 26, "title": "Task 26", "description": "Update project milestones", "completed": true },
    { "id": 27, "title": "Task 27", "description": "Organize team lunch", "completed": false },
    { "id": 28, "title": "Task 28", "description": "Update application version", "completed": true },
    { "id": 29, "title": "Task 29", "description": "Review design prototypes", "completed": false },
    { "id": 30, "title": "Task 30", "description": "Test cross-browser compatibility", "completed": true }
];